name: item_list
description: A list of items!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_bloc: ^6.1.1
  flutter_bloc: ^4.0.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
#  bloc_test: ^7.1.0
  bloc_test: ^5.0.0

flutter:
  uses-material-design: true
